version: "3.8"

services:
  fastapi:
    build:
      context: .
    command: uvicorn main_fastapi:app --host 0.0.0.0 --port ${fastapi_port} --reload
    ports:
      - "${fastapi_port}:${fastapi_port}"
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - fastapi_port=${fastapi_port}
      - secret_key=${secret_key}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs

  streamlit:
    build:
      context: .
    command: streamlit run main_streamlit.py --server.port ${streamlit_port} --server.enableCORS false
    ports:
      - "${streamlit_port}:${streamlit_port}"
    env_file:
      - .env
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - streamlit_port=${streamlit_port}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
